// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAll() {
  return window['go']['main']['App']['AcceptAll']();
}

export function AcceptFile(arg1) {
  return window['go']['main']['App']['AcceptFile'](arg1);
}

export function ApplyAIConfigGroup(arg1, arg2) {
  return window['go']['main']['App']['ApplyAIConfigGroup'](arg1, arg2);
}

export function CancelAcpPrompt(arg1) {
  return window['go']['main']['App']['CancelAcpPrompt'](arg1);
}

export function CloseAcpSession(arg1) {
  return window['go']['main']['App']['CloseAcpSession'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CopyWorkspacePaths(arg1, arg2) {
  return window['go']['main']['App']['CopyWorkspacePaths'](arg1, arg2);
}

export function CreateAcpSession(arg1) {
  return window['go']['main']['App']['CreateAcpSession'](arg1);
}

export function CreateSSHTerminal(arg1) {
  return window['go']['main']['App']['CreateSSHTerminal'](arg1);
}

export function CreateTerminal() {
  return window['go']['main']['App']['CreateTerminal']();
}

export function CreateWorkspaceFile(arg1) {
  return window['go']['main']['App']['CreateWorkspaceFile'](arg1);
}

export function CreateWorkspaceFolder(arg1) {
  return window['go']['main']['App']['CreateWorkspaceFolder'](arg1);
}

export function DeleteWorkspaceFile(arg1) {
  return window['go']['main']['App']['DeleteWorkspaceFile'](arg1);
}

export function DetectAIToolConfigPaths() {
  return window['go']['main']['App']['DetectAIToolConfigPaths']();
}

export function GetAIConfigGroups() {
  return window['go']['main']['App']['GetAIConfigGroups']();
}

export function GetAcpAgents() {
  return window['go']['main']['App']['GetAcpAgents']();
}

export function GetAppearance() {
  return window['go']['main']['App']['GetAppearance']();
}

export function GetBackgroundImageData(arg1) {
  return window['go']['main']['App']['GetBackgroundImageData'](arg1);
}

export function GetChangedFiles() {
  return window['go']['main']['App']['GetChangedFiles']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileDiff(arg1) {
  return window['go']['main']['App']['GetFileDiff'](arg1);
}

export function GetFilePreviewData(arg1) {
  return window['go']['main']['App']['GetFilePreviewData'](arg1);
}

export function GetLSPStatus(arg1) {
  return window['go']['main']['App']['GetLSPStatus'](arg1);
}

export function GetProjectRunCommands() {
  return window['go']['main']['App']['GetProjectRunCommands']();
}

export function GetRemoteWorkspaces() {
  return window['go']['main']['App']['GetRemoteWorkspaces']();
}

export function GetSSHConfigs() {
  return window['go']['main']['App']['GetSSHConfigs']();
}

export function GetStartupCommands() {
  return window['go']['main']['App']['GetStartupCommands']();
}

export function GetStartupWorkspace() {
  return window['go']['main']['App']['GetStartupWorkspace']();
}

export function GetTerminalSnapshots() {
  return window['go']['main']['App']['GetTerminalSnapshots']();
}

export function GetWorkspaceHistory() {
  return window['go']['main']['App']['GetWorkspaceHistory']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function ListRemoteDir(arg1) {
  return window['go']['main']['App']['ListRemoteDir'](arg1);
}

export function MoveWorkspacePaths(arg1, arg2) {
  return window['go']['main']['App']['MoveWorkspacePaths'](arg1, arg2);
}

export function OpenInNewWindow(arg1) {
  return window['go']['main']['App']['OpenInNewWindow'](arg1);
}

export function OpenRemoteWorkspace(arg1, arg2) {
  return window['go']['main']['App']['OpenRemoteWorkspace'](arg1, arg2);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReconnectTerminal(arg1) {
  return window['go']['main']['App']['ReconnectTerminal'](arg1);
}

export function RefreshLocalWorkspace() {
  return window['go']['main']['App']['RefreshLocalWorkspace']();
}

export function RefreshRemoteWorkspace() {
  return window['go']['main']['App']['RefreshRemoteWorkspace']();
}

export function RemoveRemoteWorkspace(arg1) {
  return window['go']['main']['App']['RemoveRemoteWorkspace'](arg1);
}

export function RemoveSSHConfig(arg1) {
  return window['go']['main']['App']['RemoveSSHConfig'](arg1);
}

export function RemoveWorkspaceFromHistory(arg1) {
  return window['go']['main']['App']['RemoveWorkspaceFromHistory'](arg1);
}

export function RenameWorkspacePath(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspacePath'](arg1, arg2);
}

export function ReplaceWorkspace(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceWorkspace'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RespondAcpPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondAcpPermission'](arg1, arg2, arg3);
}

export function RevertAll() {
  return window['go']['main']['App']['RevertAll']();
}

export function RevertFile(arg1) {
  return window['go']['main']['App']['RevertFile'](arg1);
}

export function SaveAIConfigGroups(arg1) {
  return window['go']['main']['App']['SaveAIConfigGroups'](arg1);
}

export function SaveAcpAgents(arg1) {
  return window['go']['main']['App']['SaveAcpAgents'](arg1);
}

export function SaveAppearance(arg1) {
  return window['go']['main']['App']['SaveAppearance'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveProjectRunCommands(arg1) {
  return window['go']['main']['App']['SaveProjectRunCommands'](arg1);
}

export function SaveRemoteWorkspace(arg1) {
  return window['go']['main']['App']['SaveRemoteWorkspace'](arg1);
}

export function SaveSSHConfig(arg1) {
  return window['go']['main']['App']['SaveSSHConfig'](arg1);
}

export function SaveStartupCommands(arg1) {
  return window['go']['main']['App']['SaveStartupCommands'](arg1);
}

export function SaveTerminalSnapshots(arg1) {
  return window['go']['main']['App']['SaveTerminalSnapshots'](arg1);
}

export function SearchWorkspace(arg1, arg2) {
  return window['go']['main']['App']['SearchWorkspace'](arg1, arg2);
}

export function SelectBackgroundImage() {
  return window['go']['main']['App']['SelectBackgroundImage']();
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendAcpPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendAcpPrompt'](arg1, arg2);
}

export function SendLSPMessage(arg1, arg2) {
  return window['go']['main']['App']['SendLSPMessage'](arg1, arg2);
}

export function SetAcpSessionMode(arg1, arg2) {
  return window['go']['main']['App']['SetAcpSessionMode'](arg1, arg2);
}

export function StartLSP(arg1) {
  return window['go']['main']['App']['StartLSP'](arg1);
}

export function StopLSP(arg1) {
  return window['go']['main']['App']['StopLSP'](arg1);
}

export function UploadWorkspaceFiles(arg1) {
  return window['go']['main']['App']['UploadWorkspaceFiles'](arg1);
}

export function UploadWorkspacePaths(arg1, arg2) {
  return window['go']['main']['App']['UploadWorkspacePaths'](arg1, arg2);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
