// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {snapshot} from '../models';
import {lsp} from '../models';

export function AcceptAll():Promise<void>;

export function AcceptFile(arg1:string):Promise<void>;

export function ApplyAIConfigGroup(arg1:config.AIConfigGroup,arg2:string):Promise<void>;

export function CancelAcpPrompt(arg1:string):Promise<void>;

export function CloseAcpSession(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CopyWorkspacePaths(arg1:Array<string>,arg2:string):Promise<void>;

export function CreateAcpSession(arg1:string):Promise<main.AcpSessionInfo>;

export function CreateSSHTerminal(arg1:main.SSHConfig):Promise<string>;

export function CreateTerminal():Promise<string>;

export function CreateWorkspaceFile(arg1:string):Promise<void>;

export function CreateWorkspaceFolder(arg1:string):Promise<void>;

export function DeleteWorkspaceFile(arg1:string):Promise<void>;

export function DetectAIToolConfigPaths():Promise<main.AIToolPaths>;

export function GetAIConfigGroups():Promise<Array<config.AIConfigGroup>>;

export function GetAcpAgents():Promise<Array<config.AcpAgentConfig>>;

export function GetAppearance():Promise<config.Appearance>;

export function GetBackgroundImageData(arg1:string):Promise<string>;

export function GetChangedFiles():Promise<Array<snapshot.FileChange>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileDiff(arg1:string):Promise<Record<string, string>>;

export function GetFilePreviewData(arg1:string):Promise<string>;

export function GetLSPStatus(arg1:string):Promise<lsp.ServerInfo>;

export function GetProjectRunCommands():Promise<Array<config.ProjectRunCommand>>;

export function GetRemoteWorkspaces():Promise<Array<config.RemoteWorkspaceEntry>>;

export function GetSSHConfigs():Promise<Array<config.SSHConfig>>;

export function GetStartupCommands():Promise<Array<config.StartupCommand>>;

export function GetStartupWorkspace():Promise<string>;

export function GetTerminalSnapshots():Promise<Array<config.TerminalSnapshot>>;

export function GetWorkspaceHistory():Promise<Array<config.WorkspaceEntry>>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function ListRemoteDir(arg1:string):Promise<Array<main.RemoteDirEntry>>;

export function MoveWorkspacePaths(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenInNewWindow(arg1:string):Promise<void>;

export function OpenRemoteWorkspace(arg1:main.SSHConfig,arg2:string):Promise<main.WorkspaceInfo>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceInfo>;

export function ReconnectTerminal(arg1:config.TerminalSnapshot):Promise<string>;

export function RefreshLocalWorkspace():Promise<main.WorkspaceInfo>;

export function RefreshRemoteWorkspace():Promise<main.WorkspaceInfo>;

export function RemoveRemoteWorkspace(arg1:string):Promise<void>;

export function RemoveSSHConfig(arg1:string):Promise<void>;

export function RemoveWorkspaceFromHistory(arg1:string):Promise<void>;

export function RenameWorkspacePath(arg1:string,arg2:string):Promise<void>;

export function ReplaceWorkspace(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondAcpPermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RevertAll():Promise<void>;

export function RevertFile(arg1:string):Promise<void>;

export function SaveAIConfigGroups(arg1:Array<config.AIConfigGroup>):Promise<void>;

export function SaveAcpAgents(arg1:Array<config.AcpAgentConfig>):Promise<void>;

export function SaveAppearance(arg1:config.Appearance):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveProjectRunCommands(arg1:Array<config.ProjectRunCommand>):Promise<void>;

export function SaveRemoteWorkspace(arg1:config.RemoteWorkspaceEntry):Promise<void>;

export function SaveSSHConfig(arg1:config.SSHConfig):Promise<void>;

export function SaveStartupCommands(arg1:Array<config.StartupCommand>):Promise<void>;

export function SaveTerminalSnapshots(arg1:Array<config.TerminalSnapshot>):Promise<void>;

export function SearchWorkspace(arg1:string,arg2:boolean):Promise<Array<main.WorkspaceSearchResult>>;

export function SelectBackgroundImage():Promise<string>;

export function SelectWorkspace():Promise<main.WorkspaceInfo>;

export function SendAcpPrompt(arg1:string,arg2:string):Promise<void>;

export function SendLSPMessage(arg1:string,arg2:string):Promise<void>;

export function SetAcpSessionMode(arg1:string,arg2:string):Promise<void>;

export function StartLSP(arg1:string):Promise<void>;

export function StopLSP(arg1:string):Promise<void>;

export function UploadWorkspaceFiles(arg1:string):Promise<void>;

export function UploadWorkspacePaths(arg1:Array<string>,arg2:string):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
